# Generated by Django 3.2 on 2022-03-08 22:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='Text for post...', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 2, 15, 33, 489506)),
        ),
        migrations.AlterUniqueTogether(
            name='twitter',
            unique_together={('follow', 'followed')},
        ),
    ]
