# Generated by Django 4.0.3 on 2022-03-29 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_message_mes_created_alter_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mes_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 11, 13, 16, 581539)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 11, 13, 16, 580539)),
        ),
    ]
