# Generated by Django 4.0.3 on 2022-04-01 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_comment_mes_created_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mes_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 20, 48, 5, 296807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 20, 48, 5, 294802, tzinfo=utc)),
        ),
    ]
